/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package metodoaleatoriocongruencialmixto;

import com.sun.org.apache.bcel.internal.generic.BREAKPOINT;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author CRISTIAN
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }

    
    ArrayList<tablas> lista= new ArrayList<tablas>();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tx = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tm = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ta = new javax.swing.JTextField();
        btempezar = new javax.swing.JButton();
        btnuevo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("GENERACION DE NUMEROS RECTANGULARES METODO CONGRUENCIAL MULTIPLICATIVO");

        jLabel3.setText("Xo>0=");

        tx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txActionPerformed(evt);
            }
        });

        jLabel4.setText("m>Xo,a,c=");

        tm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmActionPerformed(evt);
            }
        });

        jLabel5.setText("a>0=");

        btempezar.setText("EMPEZAR");
        btempezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btempezarActionPerformed(evt);
            }
        });

        btnuevo.setText("NUEVO");
        btnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuevoActionPerformed(evt);
            }
        });

        jLabel7.setText("Cuantos numeros desea genrar?");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Recuerde que x, a y c tienen que\nser numeros impares y menores\nque m.");
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnuevo)
                .addGap(18, 18, 18)
                .addComponent(btempezar)
                .addGap(54, 54, 54))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ta, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                        .addComponent(tx)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(242, 242, 242))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tm, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(tx, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ta, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 50, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(19, 19, 19)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btempezar)
                    .addComponent(btnuevo))
                .addGap(21, 21, 21))
        );

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "n", "Xn", "Xn+1", "Numeros Uniformes"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jLabel2.setText("INGRESE LOS DATOS INICIALES DE Xn+1=aXnmod m  ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txActionPerformed

    private void tmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tmActionPerformed

    private void btempezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btempezarActionPerformed

        
        if (primo(tm.getText())==false){
        
            JOptionPane.showMessageDialog(rootPane, "INGRESE UN NUMERO PRIMO EN M");
            tm.setText("");
            tm.requestFocus();
        
        }
        if(seleccionx(tx.getText(),tm.getText())==false){
        JOptionPane.showMessageDialog(rootPane, "INGRESE UN NUMERO MENOR QUE M");
            ta.setText("");
            ta.requestFocus();
        }
        
        if(selecciona(ta.getText())==false){
        JOptionPane.showMessageDialog(rootPane, "INGRESE UN NUMERO IMPAR EN a");
            ta.setText("");
            ta.requestFocus();
        }
       
        if (primo(tm.getText())&&seleccionx(tx.getText(),tm.getText())&&selecciona(ta.getText())) {
          int cant= Integer.parseInt(cantidad.getText());
                int m = Integer.parseInt(tm.getText());
                double x = Double.parseDouble(tx.getText());
                int a = Integer.parseInt(ta.getText());
                
                double xe;
                double ale;
           
         
            for (int i = 0; i < cant; i++) {
                xe=(a*x)%m;
                ale=xe/m;
                 tablas tab= new tablas(Integer.toString(i),String.format("%.0f", x),String.format("%.0f", xe),String.format("%.2f", ale));
        lista.add(tab);  
         mostrar();
              
              x=xe;
      
               
                
                
                
            }
           
         
         
        }
      
        
    }//GEN-LAST:event_btempezarActionPerformed

    private void btnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuevoActionPerformed
        // TODO add your handling code here:

        tx.setText(null);
        tm.setText(null);
        ta.setText(null);

        tx.setFocusable(true);
       

    }//GEN-LAST:event_btnuevoActionPerformed

    public void generar(){
    
    
    
    
    }
    
    public boolean seleccionx(String r,String p){
    boolean a=true;
     int n = Integer.parseInt(r);
     int m = Integer.parseInt(p);
        if (n>m) {
            a=false;
        }
    return a;
    }
    
  
    public boolean selecciona(String r){
    boolean a=true;
     int n = Integer.parseInt(r);
     n=n%2;
        if (n==0) {
            a=false;
        }
    return a;
    }
    
     public boolean seleccionc(String r,String m){
    boolean a=true;
     int n = Integer.parseInt(r);
     int o = Integer.parseInt(m);
     n=n%2;
     o=n%o;
        if (n==0 || o==0) {
            a=false;
        }
    return a;
    }
    
    public void mostrar(){
    String matris[][]= new String[lista.size()][4];
    
        for (int i = 0; i <lista.size(); i++) {
            matris[i][0]= lista.get(i).getXe();
            matris[i][1]= lista.get(i).getA();
            matris[i][2]= lista.get(i).getM();
            matris[i][3]= lista.get(i).getN();
            
        }
        
        tabla.setModel(new javax.swing.table.DefaultTableModel(
           matris,
            new String [] {
                "n", "Xn", "Xn+1", "Numeros Uniformes"
            }
        ));
    
    }
    
     public boolean primo(String r){
        int n = Integer.parseInt(r);
        int d=0,np=0,p=0;
        boolean esPrimo=false;
         if (n==2) {
            esPrimo=true; 
         }
          if (n==3) {
            esPrimo=true; 
         }
         if (n>3) {
             d=n%2;
             np=n%3;
             p=n%7;
         }
         if ((d!=0 && np!=0 && p!=0)||n==7) {
             esPrimo=true; 
         }
    
         
         
         return esPrimo;
 
     }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btempezar;
    private javax.swing.JButton btnuevo;
    private javax.swing.JTextField cantidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField ta;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField tm;
    public javax.swing.JTextField tx;
    // End of variables declaration//GEN-END:variables
}
